allowBuilds:
  es5-ext: false
overrides:
  abab: npm:@nolyfill/abab@^1
  array-flatten: npm:@nolyfill/array-flatten@^1
  es-set-tostringtag: npm:@nolyfill/es-set-tostringtag@^1
  globalthis: npm:@nolyfill/globalthis@^1
  is-core-module: npm:@nolyfill/is-core-module@^1
  isarray: npm:@nolyfill/isarray@^1
  safe-buffer: npm:@nolyfill/safe-buffer@^1
  safer-buffer: npm:@nolyfill/safer-buffer@^1
  side-channel: npm:@nolyfill/side-channel@^1
  hasown: npm:@nolyfill/hasown@^1
